window.QUIZ_DATA = {
 "per_level": 5,
 "total_levels": 40,
 "questions": [
  {
   "id": 1,
   "level": 1,
   "text": "人工智能的英文缩写是？",
   "option_a": "PC",
   "option_b": "AI",
   "option_c": "iPad",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 2,
   "level": 1,
   "text": "豆包、智能对话机器人属于什么类型工具？",
   "option_a": "人工智能",
   "option_b": "办公软件",
   "option_c": "游戏软件",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 3,
   "level": 1,
   "text": "我们给AI下达任务、描述需求的文字统称？",
   "option_a": "提示词",
   "option_b": "代码",
   "option_c": "口令",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 4,
   "level": 1,
   "text": "AI本身是否具备真实的人类情感？",
   "option_a": "有喜怒哀乐",
   "option_b": "没有，仅模拟表达",
   "option_c": "只有开心情绪",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 5,
   "level": 1,
   "text": "想要AI生成专属绘画作品，我们需要？",
   "option_a": "详细文字描述画面",
   "option_b": "发送隐私信息",
   "option_c": "随意输入符号",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 6,
   "level": 2,
   "text": "小学生使用AI完成作业的正确方式是？",
   "option_a": "抄全部答案",
   "option_b": "参考思路独立完成",
   "option_c": "让AI代考",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 7,
   "level": 2,
   "text": "以下不属于AI产品的是？",
   "option_a": "智能音箱",
   "option_b": "纸质笔记本",
   "option_c": "人脸识别门锁",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 8,
   "level": 2,
   "text": "和AI互动时，绝对不能发送的是？",
   "option_a": "学习问题",
   "option_b": "家庭住址、身份证号",
   "option_c": "作文需求",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 9,
   "level": 2,
   "text": "AI学习和积累知识的核心依靠是？",
   "option_a": "海量数据+算法",
   "option_b": "自主观察世界",
   "option_c": "人类大脑记忆",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 10,
   "level": 2,
   "text": "手机人脸解锁、人脸打卡运用的核心技术是？",
   "option_a": "AI图像识别",
   "option_b": "放大镜成像",
   "option_c": "手动对比",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 11,
   "level": 3,
   "text": "关于AI生成图片，说法正确的是？",
   "option_a": "场景不一定真实存在",
   "option_b": "都是实拍照片",
   "option_c": "可直接作为科学证据",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 12,
   "level": 3,
   "text": "如何提问能让AI给出最准确的答案？",
   "option_a": "清晰完整描述问题",
   "option_b": "只发单个字",
   "option_c": "输入乱码",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 13,
   "level": 3,
   "text": "下列哪项是AI无法做到的？",
   "option_a": "写小故事",
   "option_b": "解答科普问题",
   "option_c": "凭空制造实物玩具",
   "option_d": "",
   "answer": "C",
   "explanation": ""
  },
  {
   "id": 14,
   "level": 3,
   "text": "面对AI给出的答案，我们应该？",
   "option_a": "全盘相信",
   "option_b": "辨别对错、理性参考",
   "option_c": "直接转发",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 15,
   "level": 3,
   "text": "适合借助AI完成的学习任务是？",
   "option_a": "构思作文提纲",
   "option_b": "代替期末考试",
   "option_c": "抄写作业答案",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 16,
   "level": 4,
   "text": "AI程序运行必须依托的设备是？",
   "option_a": "电子设备（手机/电脑）",
   "option_b": "纸质书本",
   "option_c": "文具",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 17,
   "level": 4,
   "text": "主流AI机器人最擅长识别的人类语言是？",
   "option_a": "普通话",
   "option_b": "动物语言",
   "option_c": "无声手势",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 18,
   "level": 4,
   "text": "使用AI的文明行为是？",
   "option_a": "请教学习难题",
   "option_b": "生成暴力内容",
   "option_c": "恶意骚扰AI",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 19,
   "level": 4,
   "text": "AI绘画的核心功能是？",
   "option_a": "根据文字生成图画",
   "option_b": "手动手绘图片",
   "option_c": "冲洗照片",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 20,
   "level": 4,
   "text": "关于AI对话记录，说法正确的是？",
   "option_a": "可能被留存，禁止发隐私",
   "option_b": "会立刻自动消失",
   "option_c": "所有人都能看见",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 21,
   "level": 5,
   "text": "手机导航自动规划最优路线，运用了？",
   "option_a": "AI智能算法",
   "option_b": "随机猜测",
   "option_c": "人工记忆",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 22,
   "level": 5,
   "text": "发现AI答案明显错误时，应该？",
   "option_a": "直接采信",
   "option_b": "查阅资料核实",
   "option_c": "传播错误内容",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 23,
   "level": 5,
   "text": "以下不属于AI创作的是？",
   "option_a": "手写日记",
   "option_b": "AI写诗",
   "option_c": "AI编童话",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 24,
   "level": 5,
   "text": "能否让AI冒充家长和老师沟通？",
   "option_a": "不可以，属于不诚信行为",
   "option_b": "方便时可以",
   "option_c": "偶尔可以",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 25,
   "level": 5,
   "text": "AI的知识来源是？",
   "option_a": "整合已有数据",
   "option_b": "自主发明新知识",
   "option_c": "凭空创造",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 26,
   "level": 6,
   "text": "短视频平台自动推送喜欢的视频，依靠？",
   "option_a": "AI推荐技术",
   "option_b": "人工筛选",
   "option_c": "系统随机",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 27,
   "level": 6,
   "text": "让AI修改作文，效果最好的做法是？",
   "option_a": "明确修改要求",
   "option_b": "只发半篇作文",
   "option_c": "无要求直接发送",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 28,
   "level": 6,
   "text": "对待AI生成作文的正确做法是？",
   "option_a": "借鉴思路自主改写",
   "option_b": "一字不改直接上交",
   "option_c": "冒充原创发表",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 29,
   "level": 6,
   "text": "智能扫地机器人避障功能依靠？",
   "option_a": "AI感知识别",
   "option_b": "视觉眼睛",
   "option_c": "嗅觉探测",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 30,
   "level": 6,
   "text": "我们应该将AI定义为？",
   "option_a": "人类的学习辅助工具",
   "option_b": "完美无缺的智者",
   "option_c": "可以替代人类的存在",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 31,
   "level": 7,
   "text": "不适合借助AI学习的内容是？",
   "option_a": "不文明段子、恶作剧方法",
   "option_b": "词语解释",
   "option_c": "科学小知识",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 32,
   "level": 7,
   "text": "英文Prompt的中文通用名称是？",
   "option_a": "提示词",
   "option_b": "指令码",
   "option_c": "文件夹",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 33,
   "level": 7,
   "text": "AI模拟的情绪属于？",
   "option_a": "文字模仿，无真实感受",
   "option_b": "真实喜怒哀乐",
   "option_c": "自主情绪变化",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 34,
   "level": 7,
   "text": "纯手动直尺画图属于AI应用吗？",
   "option_a": "不属于",
   "option_b": "属于",
   "option_c": "部分属于",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 35,
   "level": 7,
   "text": "AI翻译的主要作用是？",
   "option_a": "辅助理解多国语言",
   "option_b": "结果绝对准确",
   "option_c": "替代语言学习",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 36,
   "level": 8,
   "text": "向AI请教习题的核心目的是？",
   "option_a": "弄懂解题思路",
   "option_b": "只抄最终答案",
   "option_c": "节省思考时间",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 37,
   "level": 8,
   "text": "AI识别图片中动物、植物的技术是？",
   "option_a": "图像识别",
   "option_b": "图像复印",
   "option_c": "图像放大",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 38,
   "level": 8,
   "text": "AI换脸视频最大的隐患是？",
   "option_a": "伪造画面，误导他人",
   "option_b": "画质模糊",
   "option_c": "播放卡顿",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 39,
   "level": 8,
   "text": "学习中对待AI的核心态度是？",
   "option_a": "辅助学习，不依赖",
   "option_b": "全程替代自己思考",
   "option_c": "完全拒绝使用",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 40,
   "level": 8,
   "text": "普通AI无法完成的行为是？",
   "option_a": "线下运动、上课",
   "option_b": "整理资料",
   "option_c": "解答问题",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 41,
   "level": 9,
   "text": "智能手表语音问答功能依托？",
   "option_a": "AI语音识别技术",
   "option_b": "手动输入",
   "option_c": "网络随机回复",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 42,
   "level": 9,
   "text": "创作小故事不需要给AI提供？",
   "option_a": "银行卡密码",
   "option_b": "故事主题",
   "option_c": "主角设定",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 43,
   "level": 9,
   "text": "AI编造虚假、不存在信息的现象被称为？",
   "option_a": "AI幻觉",
   "option_b": "AI出错",
   "option_c": "AI休眠",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 44,
   "level": 9,
   "text": "最规范的AI使用学习习惯是？",
   "option_a": "先思考，后求助",
   "option_b": "遇题直接找AI",
   "option_c": "完全不用AI",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 45,
   "level": 9,
   "text": "AI语音翻译可以实现的功能是？",
   "option_a": "中英文互转",
   "option_b": "听懂动物语言",
   "option_c": "改变语言天赋",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 46,
   "level": 10,
   "text": "考试期间使用AI答题属于什么行为？",
   "option_a": "作弊违规",
   "option_b": "正常学习",
   "option_c": "合理求助",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 47,
   "level": 10,
   "text": "关于AI生成内容的版权，说法正确的是？",
   "option_a": "不可随意冒充原创商用",
   "option_b": "生成即归个人所有",
   "option_c": "可随意发布售卖",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 48,
   "level": 10,
   "text": "交通摄像头识别违章车辆运用了？",
   "option_a": "AI图像识别",
   "option_b": "人工肉眼监控",
   "option_c": "高清放大",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 49,
   "level": 10,
   "text": "想要AI绘画效果更好，需要？",
   "option_a": "细化画面描述提示词",
   "option_b": "简化所有要求",
   "option_c": "不输入任何描述",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 50,
   "level": 10,
   "text": "AI区别于普通计算器的核心优势是？",
   "option_a": "能理解语言、完成多元任务",
   "option_b": "计算速度更快",
   "option_c": "只能做数学计算",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 51,
   "level": 11,
   "text": "禁止要求AI生成的内容是？",
   "option_a": "虚假谣言、暴力内容",
   "option_b": "手抄报素材",
   "option_c": "古诗赏析",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 52,
   "level": 11,
   "text": "AI技术进步的核心动力是？",
   "option_a": "人类持续研发更新",
   "option_b": "自主进化升级",
   "option_c": "网络自动更新",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 53,
   "level": 11,
   "text": "AI听不懂问题时，正确做法是？",
   "option_a": "重新清晰组织语言提问",
   "option_b": "重复刷屏发送",
   "option_c": "言语催促辱骂",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 54,
   "level": 11,
   "text": "AI绘画、AI写作属于哪类AI？",
   "option_a": "生成式AI",
   "option_b": "传统计算器AI",
   "option_c": "监控AI",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 55,
   "level": 11,
   "text": "使用AI学习最需要保留的能力是？",
   "option_a": "独立思考",
   "option_b": "完全依赖AI",
   "option_c": "放弃动脑",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 56,
   "level": 12,
   "text": "嘈杂环境会对AI语音识别造成什么影响？",
   "option_a": "准确率降低",
   "option_b": "准确率提升",
   "option_c": "无任何影响",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 57,
   "level": 12,
   "text": "大模型AI能够同时理解文字和图片，这种能力被称为？",
   "option_a": "多模态",
   "option_b": "单模态",
   "option_c": "无模态",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 58,
   "level": 12,
   "text": "使用AI生成图片后，正确的做法是？",
   "option_a": "注明由AI生成，不冒充原创",
   "option_b": "直接署上自己的名字",
   "option_c": "随意商用赚钱",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 59,
   "level": 12,
   "text": "AI机器人需要通过什么来学习和进步？",
   "option_a": "大量数据训练",
   "option_b": "自动进化",
   "option_c": "凭空出现",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 60,
   "level": 12,
   "text": "下列哪一项属于AI的合理应用？",
   "option_a": "帮助老人语音拨号",
   "option_b": "替人考试作弊",
   "option_c": "伪造新闻视频",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 61,
   "level": 13,
   "text": "地球围绕哪个天体公转？",
   "option_a": "月球",
   "option_b": "太阳",
   "option_c": "火星",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 62,
   "level": 13,
   "text": "下列属于哺乳动物的是？",
   "option_a": "鲸鱼",
   "option_b": "公鸡",
   "option_c": "鳄鱼",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 63,
   "level": 13,
   "text": "一年共有几个季节？",
   "option_a": "3个",
   "option_b": "4个",
   "option_c": "5个",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 64,
   "level": 13,
   "text": "标准大气压下，水结冰的温度是？",
   "option_a": "0℃",
   "option_b": "10℃",
   "option_c": "100℃",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 65,
   "level": 13,
   "text": "鸟类最核心的特征是拥有？",
   "option_a": "翅膀",
   "option_b": "羽毛",
   "option_c": "喙",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 66,
   "level": 14,
   "text": "太阳系中体积最大的行星是？",
   "option_a": "地球",
   "option_b": "木星",
   "option_c": "水星",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 67,
   "level": 14,
   "text": "“举头望明月，低头思故乡”的作者是？",
   "option_a": "李白",
   "option_b": "杜甫",
   "option_c": "白居易",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 68,
   "level": 14,
   "text": "昼夜交替现象的成因是？",
   "option_a": "地球自转",
   "option_b": "地球公转",
   "option_c": "月球转动",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 69,
   "level": 14,
   "text": "人体面积最大的器官是？",
   "option_a": "心脏",
   "option_b": "皮肤",
   "option_c": "大脑",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 70,
   "level": 14,
   "text": "下列属于可再生能源的是？",
   "option_a": "太阳能",
   "option_b": "煤炭",
   "option_c": "石油",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 71,
   "level": 15,
   "text": "黄河最终流入的海域是？",
   "option_a": "渤海",
   "option_b": "东海",
   "option_c": "南海",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 72,
   "level": 15,
   "text": "蜻蜓点水的目的是？",
   "option_a": "喝水",
   "option_b": "产卵",
   "option_c": "嬉戏",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 73,
   "level": 15,
   "text": "直角的度数是？",
   "option_a": "90°",
   "option_b": "180°",
   "option_c": "360°",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 74,
   "level": 15,
   "text": "大熊猫的主要食物是？",
   "option_a": "青草",
   "option_b": "竹子",
   "option_c": "树叶",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 75,
   "level": 15,
   "text": "北半球白昼最长的节气是？",
   "option_a": "夏至",
   "option_b": "冬至",
   "option_c": "春分",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 76,
   "level": 16,
   "text": "传说中创造汉字的人物是？",
   "option_a": "仓颉",
   "option_b": "炎帝",
   "option_c": "大禹",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 77,
   "level": 16,
   "text": "植物光合作用需要的气体是？",
   "option_a": "二氧化碳",
   "option_b": "氧气",
   "option_c": "氮气",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 78,
   "level": 16,
   "text": "企鹅的主要栖息地是？",
   "option_a": "北极",
   "option_b": "南极",
   "option_c": "赤道",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 79,
   "level": 16,
   "text": "“三人行，必有我师焉”出自？",
   "option_a": "《论语》",
   "option_b": "《孟子》",
   "option_c": "《大学》",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 80,
   "level": 16,
   "text": "我们先看到闪电后听到雷声，是因为？",
   "option_a": "光速大于声速",
   "option_b": "闪电更近",
   "option_c": "雷声延迟",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 81,
   "level": 17,
   "text": "下列属于农业益虫的是？",
   "option_a": "七星瓢虫",
   "option_b": "蝗虫",
   "option_c": "蚜虫",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 82,
   "level": 17,
   "text": "我国的首都是？",
   "option_a": "上海",
   "option_b": "北京",
   "option_c": "广州",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 83,
   "level": 17,
   "text": "彩虹一共有几种基础颜色？",
   "option_a": "5种",
   "option_b": "7种",
   "option_c": "9种",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 84,
   "level": 17,
   "text": "水的化学式是？",
   "option_a": "H₂O",
   "option_b": "CO₂",
   "option_c": "O₂",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 85,
   "level": 17,
   "text": "月亮是什么天体？",
   "option_a": "恒星",
   "option_b": "行星",
   "option_c": "卫星",
   "option_d": "",
   "answer": "C",
   "explanation": ""
  },
  {
   "id": 86,
   "level": 18,
   "text": "一年有多少个节气？",
   "option_a": "12个",
   "option_b": "24个",
   "option_c": "36个",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 87,
   "level": 18,
   "text": "人体最坚硬的部位是？",
   "option_a": "骨头",
   "option_b": "牙齿",
   "option_c": "指甲",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 88,
   "level": 18,
   "text": "西湖位于我国哪个城市？",
   "option_a": "苏州",
   "option_b": "杭州",
   "option_c": "南京",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 89,
   "level": 18,
   "text": "萤火虫发光的主要目的是？",
   "option_a": "照明",
   "option_b": "求偶交流",
   "option_c": "散热",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 90,
   "level": 18,
   "text": "植物进行呼吸作用的时间是？",
   "option_a": "白天",
   "option_b": "夜晚",
   "option_c": "全天",
   "option_d": "",
   "answer": "C",
   "explanation": ""
  },
  {
   "id": 91,
   "level": 19,
   "text": "体温计的常规量程是？",
   "option_a": "0-100℃",
   "option_b": "35-42℃",
   "option_c": "20-50℃",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 92,
   "level": 19,
   "text": "铅笔芯的主要成分是？",
   "option_a": "铅",
   "option_b": "石墨",
   "option_c": "碳纳米管",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 93,
   "level": 19,
   "text": "我国最大的淡水湖是？",
   "option_a": "洞庭湖",
   "option_b": "鄱阳湖",
   "option_c": "太湖",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 94,
   "level": 19,
   "text": "汽车刹车人前倾是因为？",
   "option_a": "惯性",
   "option_b": "重力",
   "option_c": "浮力",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 95,
   "level": 19,
   "text": "下列属于绝缘体的是？",
   "option_a": "铜丝",
   "option_b": "塑料",
   "option_c": "铁丝",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 96,
   "level": 20,
   "text": "地球公转一周的时间是？",
   "option_a": "一天",
   "option_b": "一个月",
   "option_c": "一年",
   "option_d": "",
   "answer": "C",
   "explanation": ""
  },
  {
   "id": 97,
   "level": 20,
   "text": "地球自转一周的时间是？",
   "option_a": "12小时",
   "option_b": "24小时",
   "option_c": "36小时",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 98,
   "level": 20,
   "text": "仙人掌长刺的主要作用是？",
   "option_a": "美观",
   "option_b": "减少水分蒸发",
   "option_c": "防御动物",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 99,
   "level": 20,
   "text": "五星红旗红色象征？",
   "option_a": "光明",
   "option_b": "革命",
   "option_c": "和平",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 100,
   "level": 20,
   "text": "我国四大名著不包括？",
   "option_a": "《诗经》",
   "option_b": "《西游记》",
   "option_c": "《红楼梦》",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 101,
   "level": 21,
   "text": "闰年全年天数是？",
   "option_a": "365天",
   "option_b": "366天",
   "option_c": "364天",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 102,
   "level": 21,
   "text": "声音在哪种介质中传播最快？",
   "option_a": "空气",
   "option_b": "水",
   "option_c": "固体",
   "option_d": "",
   "answer": "C",
   "explanation": ""
  },
  {
   "id": 103,
   "level": 21,
   "text": "蚕结茧后会变成？",
   "option_a": "蝴蝶",
   "option_b": "蚕蛾",
   "option_c": "毛毛虫",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 104,
   "level": 21,
   "text": "我国最长的内陆河是？",
   "option_a": "塔里木河",
   "option_b": "黄河",
   "option_c": "淮河",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 105,
   "level": 21,
   "text": "氧气的主要作用是？",
   "option_a": "呼吸燃烧",
   "option_b": "保温",
   "option_c": "遮光",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 106,
   "level": 22,
   "text": "下列属于可再生资源的是？",
   "option_a": "石油",
   "option_b": "风能",
   "option_c": "煤炭",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 107,
   "level": 22,
   "text": "哺乳动物的典型特征是？",
   "option_a": "卵生",
   "option_b": "胎生哺乳",
   "option_c": "两栖生活",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 108,
   "level": 22,
   "text": "秋天树叶变黄的原因是？",
   "option_a": "叶绿素减少",
   "option_b": "天气染色",
   "option_c": "树叶变质",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 109,
   "level": 22,
   "text": "元宵节的传统习俗是？",
   "option_a": "赏月",
   "option_b": "猜灯谜",
   "option_c": "扫墓",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 110,
   "level": 22,
   "text": "重阳节的传统习俗是？",
   "option_a": "登高赏菊",
   "option_b": "吃粽子",
   "option_c": "贴春联",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 111,
   "level": 23,
   "text": "人体气体交换的主要场所是？",
   "option_a": "气管",
   "option_b": "肺",
   "option_c": "鼻腔",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 112,
   "level": 23,
   "text": "我国的国球是？",
   "option_a": "篮球",
   "option_b": "乒乓球",
   "option_c": "羽毛球",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 113,
   "level": 23,
   "text": "“谁知盘中餐，粒粒皆辛苦”作者是？",
   "option_a": "李白",
   "option_b": "李绅",
   "option_c": "杜甫",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 114,
   "level": 23,
   "text": "干冰的主要成分是？",
   "option_a": "固态水",
   "option_b": "固态二氧化碳",
   "option_c": "固态氧气",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 115,
   "level": 23,
   "text": "莲藕孔洞的主要作用是？",
   "option_a": "储存空气",
   "option_b": "储存水分",
   "option_c": "美观",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 116,
   "level": 24,
   "text": "光年是什么单位？",
   "option_a": "时间单位",
   "option_b": "长度单位",
   "option_c": "速度单位",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 117,
   "level": 24,
   "text": "海水不能直接饮用的原因是？",
   "option_a": "含盐量高",
   "option_b": "有细菌",
   "option_c": "味道苦",
   "option_d": "",
   "answer": "A",
   "explanation": ""
  },
  {
   "id": 118,
   "level": 24,
   "text": "我国古代用于导航的发明是？",
   "option_a": "火药",
   "option_b": "指南针",
   "option_c": "印刷术",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 119,
   "level": 24,
   "text": "绿色植物制造养料的主要器官是？",
   "option_a": "根",
   "option_b": "叶",
   "option_c": "茎",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 120,
   "level": 24,
   "text": "地球的天然卫星是？",
   "option_a": "太阳",
   "option_b": "月球",
   "option_c": "火星",
   "option_d": "",
   "answer": "B",
   "explanation": ""
  },
  {
   "id": 121,
   "level": 25,
   "text": "AI拥有和人类一样的自主思考能力",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 122,
   "level": 25,
   "text": "智能人脸识别属于人工智能应用",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 123,
   "level": 25,
   "text": "可以向AI发送家庭住址、手机号等隐私信息",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 124,
   "level": 25,
   "text": "AI生成的内容需要人工甄别对错，不能全盘相信",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 125,
   "level": 25,
   "text": "细化提示词，能让AI输出的内容更贴合需求",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 126,
   "level": 26,
   "text": "AI具备真实的喜怒哀乐等情绪",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 127,
   "level": 26,
   "text": "考试时借助AI答题属于作弊行为",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 128,
   "level": 26,
   "text": "AI可以辅助我们构思作文、整理学习资料",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 129,
   "level": 26,
   "text": "AI可以凭空制造出真实的实物物品",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 130,
   "level": 26,
   "text": "短视频智能推荐、导航规划路线都用到了AI技术",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 131,
   "level": 27,
   "text": "手写作业、手绘图画属于AI创作内容",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 132,
   "level": 27,
   "text": "不可以利用AI冒充家长和老师沟通",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 133,
   "level": 27,
   "text": "AI的知识是自主学习、凭空创造出来的",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 134,
   "level": 27,
   "text": "AI换脸、伪造视频容易误导他人，属于不良使用行为",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 135,
   "level": 27,
   "text": "小学生使用AI的正确方式是辅助学习、独立思考",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 136,
   "level": 28,
   "text": "AI可以完全替代人类的课堂学习和动手实践",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 137,
   "level": 28,
   "text": "智能音箱、扫地机器人都属于AI智能产品",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 138,
   "level": 28,
   "text": "AI翻译可以替代英语学习，不用背诵单词",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 139,
   "level": 28,
   "text": "AI出现回答错误时，需要我们查阅资料核实修正",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 140,
   "level": 28,
   "text": "文明提问、清晰描述问题是使用AI的基本礼仪",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 141,
   "level": 29,
   "text": "AI可以生成虚假信息，这种现象被称为AI幻觉",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 142,
   "level": 29,
   "text": "嘈杂环境不会影响AI语音识别的准确率",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 143,
   "level": 29,
   "text": "可以借鉴AI作文思路，自主修改后完成作业",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 144,
   "level": 29,
   "text": "AI有自主意识，可以独立判断是非对错",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 145,
   "level": 29,
   "text": "利用AI制作虚假证件、截图是违规行为",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 146,
   "level": 30,
   "text": "AI智能练字可以辅助纠正字形，但不能替代手动练习",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 147,
   "level": 30,
   "text": "所有AI生成的内容都可以随意商用、转发",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 148,
   "level": 30,
   "text": "AI可以帮助我们梳理知识框架、制作思维导图",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 149,
   "level": 30,
   "text": "过度依赖AI会导致独立思考能力下降",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 150,
   "level": 30,
   "text": "AI可以听懂所有动物语言和无声手势",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 151,
   "level": 31,
   "text": "生成式AI可以根据文字创作图画、文章、诗歌",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 152,
   "level": 31,
   "text": "AI对话记录绝对不会被留存，可以随意发言",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 153,
   "level": 31,
   "text": "合理使用AI可以拓宽知识面，提升学习效率",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 154,
   "level": 31,
   "text": "AI可以预判人类未知的全新知识和想法",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 155,
   "level": 31,
   "text": "识别垃圾分类、违章车辆都用到AI图像识别技术",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 156,
   "level": 32,
   "text": "AI辅助学习的核心是偷懒省事、应付作业",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 157,
   "level": 32,
   "text": "AI没有真实的生活体验和情感共情能力",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 158,
   "level": 32,
   "text": "可以让AI生成暴力、造谣、低俗的不良内容",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 159,
   "level": 32,
   "text": "AI是人类编写的程序，发展主导者是人类",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 160,
   "level": 32,
   "text": "小学生使用AI的底线是诚信、文明、守法",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 161,
   "level": 33,
   "text": "地球自转形成了昼夜交替现象",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 162,
   "level": 33,
   "text": "鲸鱼是鱼类，不是哺乳动物",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 163,
   "level": 33,
   "text": "标准大气压下，水的沸点是100℃",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 164,
   "level": 33,
   "text": "企鹅生活在北极，北极熊生活在南极",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 165,
   "level": 33,
   "text": "植物光合作用可以吸收二氧化碳，释放氧气",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 166,
   "level": 34,
   "text": "光速传播速度比声速快",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 167,
   "level": 34,
   "text": "大熊猫是食肉目动物，主食是竹子",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 168,
   "level": 34,
   "text": "黄河是我国第一长河",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 169,
   "level": 34,
   "text": "直角的度数是90度",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 170,
   "level": 34,
   "text": "月亮本身不会发光，只能反射太阳光",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 171,
   "level": 35,
   "text": "一年有24个节气",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 172,
   "level": 35,
   "text": "人体最大的消化腺是胃",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 173,
   "level": 35,
   "text": "太阳能、风能都属于可再生能源",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 174,
   "level": 35,
   "text": "蜻蜓点水是为了喝水",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 175,
   "level": 35,
   "text": "所有鸟类都有羽毛",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 176,
   "level": 36,
   "text": "木星是太阳系体积最大的行星",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 177,
   "level": 36,
   "text": "“三人行，必有我师焉”出自《论语》",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 178,
   "level": 36,
   "text": "皮肤是人体面积最大的器官",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 179,
   "level": 36,
   "text": "立夏是夏季的第一个节气",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 180,
   "level": 36,
   "text": "蝗虫是农业益虫，能保护庄稼",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 181,
   "level": 37,
   "text": "海水含盐量高，不能直接饮用",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 182,
   "level": 37,
   "text": "指南针静止时一端指向地理北极",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 183,
   "level": 37,
   "text": "莲藕的孔洞是为了储存水分",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 184,
   "level": 37,
   "text": "小狗夏天吐舌头是为了散热降温",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 185,
   "level": 37,
   "text": "光年是计算时间的单位",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 186,
   "level": 38,
   "text": "我国国花是牡丹",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 187,
   "level": 38,
   "text": "铅笔芯含有大量金属铅",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 188,
   "level": 38,
   "text": "平面镜成像是正立等大的虚像",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 189,
   "level": 38,
   "text": "闰年有366天，平年有365天",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 190,
   "level": 38,
   "text": "声音可以在真空中传播",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 191,
   "level": 39,
   "text": "水稻、小麦属于粮食作物",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 192,
   "level": 39,
   "text": "地球公转形成四季变化",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 193,
   "level": 39,
   "text": "清明节既是节气也是传统节日",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 194,
   "level": 39,
   "text": "人体呼吸气体交换的场所是鼻腔",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 195,
   "level": 39,
   "text": "乒乓球是我国的国球",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 196,
   "level": 40,
   "text": "干冰是固态的水",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "B",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 197,
   "level": 40,
   "text": "惯性可以让运动的物体保持运动状态",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 198,
   "level": 40,
   "text": "塑料、橡胶都是绝缘体",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 199,
   "level": 40,
   "text": "我国最大的城市是上海",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  },
  {
   "id": 200,
   "level": 40,
   "text": "植物只在白天进行光合作用",
   "option_a": "正确",
   "option_b": "错误",
   "option_c": "",
   "option_d": "",
   "answer": "A",
   "explanation": "√ 正确 / × 错误"
  }
 ]
};
